### ISSUE TITLE
Always Cool mode

### ISSUE THREAD

**Issue by mikekoumas** [MiguelAngelLV/esphaier#1]
Hello thank you so much for your modifications. Just an important note that I do not know how to solve it. 
My AC only shows that is off couple minutes after pressing turn off button, after those couple minutes shows the last active mode that was at (My AC still off).
I realized that the issue starts from the esphome code. As you can see in the attached image esp always receive the last active state.
Is there any way to know when my AC is ON or OFF when I am away?
Thank you so much

![Screenshot_20191117-044609_Samsung Internet](https://user-images.githubusercontent.com/29451566/69002358-82f08800-08f6-11ea-9275-9c0ed89720a6.jpg)
![Screenshot_20191117-044852_Samsung Internet](https://user-images.githubusercontent.com/29451566/69002360-8c79f000-08f6-11ea-8392-de4d833ee1f7.jpg)

**Comment by tciesiolka** [comment]
you can try using Haier.h from my forked repository - https://github.com/tciesiolka/esphaier/blob/master/Haier.h
I identified & fixed two issues that caused same behavior at my AC system. maybe it will also work for you :)

**Comment by Oksion** [comment]
The problem of poorly determining the status (on/off) of the air conditioner is that one byte (29) defines three modes of the air conditioner. zero bit - turning on the air conditioner, third bit - turning on the "Health mode", fourh bit - compressor mode, maybe the first and second bits also control something. Although I am not a programmer, I slightly corrected the code in my fork of the EspHome component. It will work only on the eshome dev branch, since it has support for advanced control modes for the air conditioner, fan speed and airflow shutter, you can take my code and adapt it to the old version if you do not need all the functions (although the dev branch is pretty stable) . The same story with one byte for several modes applies to the airflow control of the air conditioner and special operating modes.  https://github.com/Oksion/esphaier
